#!/usr/bin/env python
import sys
import os

home_dir = os.getenv('HOME')

package_base = home_dir + r"/.dblatex/share/dblatex"

sys.path.append(home_dir+r"/.dblatex/lib/python2.7/site-packages")

from dbtexmf.dblatex import dblatex
dblatex.main(base=package_base)
